<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-language" content="pl" />
	<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
	<title>Test FB</title>
	<script type="text/javascript" src="<?php echo $this->wpUrl?>jquery.min.js"></script>
	<script type="text/javascript">
		<!-- //<![CDATA[
		// zmienne globalne
		var globals = {
			ajaxUrl: "<?php echo $this->ajax?>",
			appUrl: "<?php echo $this->appUrl?>",
			wpUrl: "<?php echo $this->wpUrl?>",
			protocol: "<?php echo PROTOCOL?>",
		};
		// ]]> -->
	</script>
	<script type="text/javascript" src="<?php echo $this->wpUrl?>script.js?v=1"></script>
	<?php echo $this->headScript() ?>
</head>
<body>
	<div id="main">
		<div id="col">
			<?php echo $this->partial('partials/menu.phtml', array('sg' => $this->appUrl)); ?>
			<?php echo $this->layout()->content ?>
		</div>
	</div>

</body>
</html>
